apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-init
  namespace: togglemaster
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: evaluation-service
  namespace: togglemaster
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
  namespace: togglemaster